import './globals.css'

export const metadata = {
  title: 'Create Next App with Markdoc',
  description: 'Generated by create next app and some markdoc',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
